# 配置端口号
server:
  port: 7778

spring:
  application:
    name: config-client-test # 应用名称

# 连接数据库
  datasource: driver-class-name:com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/appdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
  username: root
  password: 123456

# 配置 Eureka Server 注册中心
eureka:
  instance:
    prefer-ip-address: true                                           # 是否使用 IP 地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}     # ip:port
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# 自定义名称
name: config-client-test
